# docker build -t goaccess/build.debian:1.4.3-10 -f Dockerfile.debian.10 .
# docker run -i --rm -v $PWD:/goaccess goaccess/build.debian:1.4.3-10 > ../goaccess.bin
FROM debian:10

RUN apt-get update -qqq
RUN apt-get install -yqqq \
    autoconf \
    build-essential \
    clang \
    gettext \
    libmaxminddb-dev \
    libssl-dev \
    linux-headers-amd64 \
    libncurses-dev \
    libgeoip-dev \
    autopoint

# GoAccess
WORKDIR /goaccess

CMD ./build-package.sh

