# docker build -t goaccess/build.ubuntu:1.4.3-20.04 -f Dockerfile.ubuntu.20.04 .
# docker run -i --rm -v $PWD:/goaccess goaccess/build.ubuntu:1.4.3-20.04 > ../goaccess.bin
FROM ubuntu:20.04

RUN apt-get update -qqq
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    autoconf \
    build-essential \
    clang \
    gettext \
    libmaxminddb-dev \
    libgeoip-dev \
    libssl-dev \
    linux-headers-generic \
    libncurses-dev \
    autopoint

# GoAccess
WORKDIR /goaccess

CMD ./build-package.sh

