# docker build -t goaccess/build.debian-10 -f Dockerfile.debian-10 .
# docker run -i --rm -v $PWD:/goaccess goaccess/build.debian-10 > goaccess
# Used to have all compile dependencies isolated in a container image.
FROM debian:10

RUN apt-get update -qqq
RUN apt-get install -yqqq \
    autoconf \
    build-essential \
    clang \
    gettext \
    libmaxminddb-dev \
    libssl-dev \
    linux-headers-amd64 \
    libncursesw5-dev \
    libgeoip-dev \
    pkg-config \
    autopoint

# GoAccess
WORKDIR /goaccess

ENTRYPOINT ["./build-dynamic.sh"]

